runtime: python
env: flex
entrypoint: python main.py
#entrypoint: gunicorn -b :$PORT --workers=5 --threads=2 main:app
runtime_config:
  python_version: 3

manual_scaling:
  instances: 1
resources:
  cpu: 1
  memory_gb: 2
  disk_size_gb: 10

# liveness_check:
#   path: "/livecheck"
#   check_interval_sec: 30
#   timeout_sec: 4
#   failure_threshold: 2
#   success_threshold: 2

# automatic_scaling:
#   min_num_instances: 1
#   max_num_instances: 2