# Connection information to the different instances
connection:
    url:
        aHR0cHM6Ly9rb2xvbmlhbC5ubw==
    useragent:
        Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/77.0.3865.90 Safari/537.36
    DB1:
        username:
            X
        password:
            Y